### ISSUE TITLE
Failed to locate 'artifact' or 'group-id' and 'artifact-id' among metadata keys with version 1.0.0

### ISSUE THREAD

**Issue by rmanibus** [quarkiverse/quarkus-playwright#74]
My app running on quarkus 3.14.2 is throwing the following exception in dev mode with gradle:

```
2024-09-25 13:34:47,754 ERROR [io.qua.dev.dep.DevUIProcessor] (build-3) Failed to process extension descriptor jar:file:///Users/loichermann/.gradle/caches/modules-2/files-2.1/io.quarkiverse.playwright/quarkus-playwright/1.0.0/e73d5230e70983d4d8d1f98cbe869b767eab7464/quarkus-playwright-1.0.0.jar!/META-INF/quarkus-extension.yaml: java.lang.RuntimeException: Failed to locate 'artifact' or 'group-id' and 'artifact-id' among metadata keys [name, description, metadata]
        at io.quarkus.devui.deployment.DevUIProcessor.getExtensionNamespace(DevUIProcessor.java:777)
        at io.quarkus.devui.deployment.DevUIProcessor.lambda$getAllExtensions$1(DevUIProcessor.java:475)
        at io.quarkus.runtime.util.ClassPathUtils.lambda$consumeAsPath$0(ClassPathUtils.java:121)
        at io.quarkus.runtime.util.ClassPathUtils.processAsPath(ClassPathUtils.java:154)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPath(ClassPathUtils.java:120)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:104)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:85)
        at io.quarkus.devui.deployment.DevUIProcessor.getAllExtensions(DevUIProcessor.java:459)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:854)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

```

**Comment by rmanibus** [comment]
Well, this is because it the quarkus-quinoa-testing was in implementation instead of testImplementation. 
This gradle file was provided by code.quarkus.io though.

**Comment by melloware** [comment]
@all-contributors add @rmanibus for test
